apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: jenishaatsupra/webreport-superset:latest
        ports:
        - containerPort: 8081
        env:
        - name: SECRET_KEY
          value: "dahm4pFDIe9yREpJLSmagZmiMpT9yOXl3GwNvp3zJaBcfP+SvHnK5yQm"
        - name: SUPERSET_ENV
          value: production
    